/**
 * Build script for Claude Academy worker.js
 * Reads HTML pages, replaces local image paths with jsDelivr CDN URLs,
 * and produces worker.js with multi-page routing ready for `wrangler deploy`.
 */

const fs = require('fs');
const path = require('path');

const CDN = 'https://cdn.jsdelivr.net/gh/agentfactory/claude-academy@main/images/';
const BASE_DIR = __dirname;

// Route map: pathname → source HTML file
const ROUTES = {
  '/': 'index.html',
  '/why-claude': 'why-claude.html',
};

// Read and transform each page
const pagesObj = {};
for (const [route, file] of Object.entries(ROUTES)) {
  let html = fs.readFileSync(path.join(BASE_DIR, file), 'utf-8');
  html = html.replace(/src="images\//g, `src="${CDN}`);
  pagesObj[route] = html;
}

const worker = `// Auto-generated by _build_worker.js — do not edit directly.
const PAGES = ${JSON.stringify(pagesObj)};

export default {
  async fetch(request) {
    const url = new URL(request.url);

    // Redirect bare /index.html to /
    if (url.pathname === '/index.html') {
      return Response.redirect(url.origin + '/', 301);
    }

    // Strip trailing slash (except root)
    if (url.pathname !== '/' && url.pathname.endsWith('/')) {
      return Response.redirect(url.origin + url.pathname.slice(0, -1), 301);
    }

    const html = PAGES[url.pathname];
    if (html) {
      return new Response(html, {
        headers: {
          'Content-Type': 'text/html;charset=UTF-8',
          'Cache-Control': 'public, max-age=3600',
          'X-Content-Type-Options': 'nosniff',
        },
      });
    }

    // 404 fallback
    return new Response(PAGES['/'], {
      status: 404,
      headers: {
        'Content-Type': 'text/html;charset=UTF-8',
        'X-Content-Type-Options': 'nosniff',
      },
    });
  },
};
`;

fs.writeFileSync(path.join(BASE_DIR, 'worker.js'), worker, 'utf-8');
console.log('worker.js built successfully!');
for (const [route, file] of Object.entries(ROUTES)) {
  console.log(`  ${route} (${file}): ${pagesObj[route].length} chars`);
}
console.log('  Output size:', worker.length, 'chars');
