/**
 * Build script for Claude Academy worker.js
 * Reads index.html, replaces local image paths with jsDelivr CDN URLs,
 * and produces worker.js ready for `wrangler deploy`.
 */

const fs = require('fs');
const path = require('path');

const CDN = 'https://cdn.jsdelivr.net/gh/agentfactory/claude-academy@main/images/';
const BASE_DIR = __dirname;

let html = fs.readFileSync(path.join(BASE_DIR, 'index.html'), 'utf-8');

// Replace local image paths with CDN URLs
html = html.replace(/src="images\//g, `src="${CDN}`);

const worker = `// Auto-generated by _build_worker.js — do not edit directly.
const HTML = ${JSON.stringify(html)};

export default {
  async fetch(request) {
    const url = new URL(request.url);

    // Redirect bare /index.html to /
    if (url.pathname === '/index.html') {
      return Response.redirect(url.origin + '/', 301);
    }

    return new Response(HTML, {
      headers: {
        'Content-Type': 'text/html;charset=UTF-8',
        'Cache-Control': 'public, max-age=3600',
        'X-Content-Type-Options': 'nosniff',
      },
    });
  },
};
`;

fs.writeFileSync(path.join(BASE_DIR, 'worker.js'), worker, 'utf-8');
console.log('worker.js built successfully!');
console.log('  HTML size:', html.length, 'chars');
console.log('  Output size:', worker.length, 'chars');
