name = "claude-academy"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "8a57c605a2514dc39c63e80531633a7e"

[[routes]]
pattern = "claudeacademy.ca/*"
zone_name = "claudeacademy.ca"

[[routes]]
pattern = "www.claudeacademy.ca/*"
zone_name = "claudeacademy.ca"
